# -*- coding: utf-8 -*-
"""Training_Model_Gaya_Belajar_Per_Modul.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oeozGVseqvVnHtkK0rKEgLgMUEqjQbT
"""

!pip install numpy==1.26.4 pandas==2.0.3 scikit-learn==1.5.2 joblib matplotlib seaborn

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("modelTraining.csv")

print("Jumlah data:", len(df))
df.head()

df = df.dropna()

assert len(df) > 50, "Data terlalu sedikit untuk training"

def label_gaya_belajar(row):
    if row["avg_completion_ratio"] >= 1.1:
        return "Fast Learner"
    elif row["avg_completion_ratio"] >= 0.85:
        return "Reflective"
    else:
        return "Consistent"

df["gaya_belajar"] = df.apply(label_gaya_belajar, axis=1)

df["gaya_belajar"].value_counts()

features = [
    "module_count",
    "total_study_duration",
    "avg_study_per_module",
    "avg_completion_ratio",
    "avg_submission_rating"
]

X = df[features]
y = df["gaya_belajar"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

tree = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)

print(classification_report(y_test, y_pred))

plt.figure(figsize=(6,5))
sns.heatmap(confusion_matrix(y_test, y_pred),
            annot=True, fmt="d",
            cmap="Blues",
            xticklabels=tree.classes_,
            yticklabels=tree.classes_)
plt.title("Confusion Matrix - Gaya Belajar (Per Modul)")
plt.show()

train_acc = accuracy_score(y_train, tree.predict(X_train))
test_acc  = accuracy_score(y_test, tree.predict(X_test))

print(f"Akurasi Training: {train_acc*100:.2f}%")
print(f"Akurasi Testing : {test_acc*100:.2f}%")

if test_acc < 0.70:
    print("STATUS: UNDERFITTING")
elif train_acc > 0.95 and train_acc - test_acc > 0.15:
    print("STATUS: OVERFITTING")
else:
    print("STATUS: GOOD FIT ✅")

plt.figure(figsize=(24,12))
plot_tree(
    tree,
    feature_names=features,
    class_names=tree.classes_,
    filled=True,
    rounded=True
)
plt.title("Decision Tree Gaya Belajar Berbasis Modul")
plt.show()

joblib.dump(tree, "model_gaya_belajar_per_modul.pkl")
print("✅ Model berhasil disimpan")

files.download("model_gaya_belajar_per_modul.pkl")